from django.urls import path
from . import views


urlpatterns =[
    path('posta/<int:id>/',views.gdx,name='gdx'),
    path('Status_pay/<int:id>/',views.Status_pay,name='Status_pay'),

    path('update/order/com/<int:id>/',views.updateordercom,name='updateordercom'),
    path('castomar/',views.castomar,name='castomar'),
    path('ajex_order_not_sh/',views.ajex_order_not_sh,name='ajex_order_not_sh'),
    path('reportpost/',views.reportpost,name='reportpost'),
    path('rnamepartener/',views.rnamepartener,name='rnamepartener'),
    path('reportpartener/<int:id>/',views.reportpartener,name='reportpartener'),
    path('dseportpartener/<int:id>/',views.dseportpartener,name='dseportpartener'),
    path('deleteDeportpartener/<int:id>/<int:di>/',views.deleteDeportpartener,name='deleteDeportpartener'),
    path('updateDeportpartener/<int:id>/<int:di>/',views.updateDeportpartener,name='updateDeportpartener'),
    path('deportpartener/<int:id>/',views.deportpartener,name='deportpartener'),
    path('castomarorder/<int:id>/',views.castomarorder,name='castomarorder'),
    path('rsreportpartener/<int:id>/',views.rsreportpartener,name='rsreportpartener'),
    path('updatepartener/<int:id>/',views.updatepartener,name='updatepartener'),
    path('deletepartener/<int:id>/',views.deletepartener,name='deletepartener'),
    path('order_admin_pdf/',views.Gennerpdf.as_view(),name='order_admin_pdf'),
    path('namepartener/',views.namepartener,name='namepartener'),
    path('dreportpost/',views.dreportpost,name='dreportpost'),
    path('posta/',views.posta,name='posta'),
    path('pdf/<int:id>/',views.pdf,name='pdf'),
    path('dsdupdate/<int:id>/',views.dsdupdate,name='dsdupdate'),
    path('Rdelete/<int:id>/',views.Rdelete,name='Rdelete'),
    path('add_to_cart',views.add_to_cart,name='add_to_cart'),
    path('ajex/',views.ajex,name='ajex'),
    path('ajexpay/',views.ajexpay,name='ajexpay'),
    path('ajexpayment/',views.ajexpayment,name='ajexpayment'),
    path('igggggggggggggg/',views.igggggggggggggg,name='igggggggggggggg'),
    path('generateKashierOrderHash/',views.generateKashierOrderHash,name='generateKashierOrderHash'),
    path('mo/',views.mo,name='mo'),
    path('es/',views.es,name='es'),
    path('mor/',views.mor,name='mor'),
    path('readMr/<int:id>/',views.readMr,name='readMr'),
    path('status/copping/<int:id>/',views.status__copping,name='status__copping'),
    path('update/copping/<int:id_order>/<int:id>/',views.update__copping,name='update__copping'),
    path('add_qty_detels/<int:id>/<int:orderdetails_id>/',views.add_qty_detels,name='add_qty_detels'),
    path('remove_from_card_detels/<int:id>/<int:orderdetails_id>/',views.remove_from_card_detels,name='remove_from_card_detels'),
    path('sub_qty_detels/<int:id>/<int:orderdetails_id>/',views.sub_qty_detels,name='sub_qty_detels'),
    path('detils_updect_color/<int:id>/<int:orderdetails_id>/',views.detils_updect_color,name='detils_updect_color'),
    path('ajex__color_detelis/<int:id>/<int:orderdetails_id>/',views.ajex__color_detelis,name='ajex__color_detelis'),
    path('show_orders_detels/<int:id>/',views.show_orders_detels,name='show_orders_detels'),
    path('add_to_Mr/<int:id>/',views.add_to_Mr,name='add_to_Mr'),
    path('MRelete/<int:id>/de/<int:mr_id>/',views.MRelete,name='MRelete'),
    path('update_mr/<int:id>/up/<int:mr_id>/',views.update_mr,name='update_mr'),
    path('send_otp',views.ressend_otp ,name='ressend_otp'),
    path('signupp',views.signupp ,name='signupp'),
    path('cart/',views.cart,name='cart'),
    path('remove_from_card/<int:orderdetails_id>',views.remove_from_card ,name='remove_from_card'),
    path('add_to_colar/<int:id>',views.add_to_colar ,name='add_to_colar'),
    path('updatePayment/<int:id>/<int:id__Paymen>',views.updatePayment ,name='updatePayment'),
    path('w_to_colar/<int:id>',views.w_to_colar ,name='w_to_colar'),
    path('updatemo/<int:id>',views.updatemo ,name='updatemo'),
    path('modelete/<int:id>',views.modelete ,name='modelete'),
    path('add_to_size/<int:id_pro>/size/<int:id_color>/',views.add_to_size ,name='add_to_size'),
    path('d_color/<int:id_pro>/color/<int:id_color>/',views.d_color ,name='d_color'),
    path('update_color/<int:id_pro>/color/<int:id_color>/',views.update_color ,name='update_color'),
    path('d_size/<int:id>/<int:id_pro>/size/<int:id_color>/',views.d_size ,name='d_size'),
    path('update_size/<int:id>/<int:id_pro>/size/<int:id_color>/',views.update_size ,name='update_size'),
    path('w_size/<int:id_pro>/size/<int:id_color>/',views.w_size ,name='w_size'),
    path('add_qty/<int:orderdetails_id>' ,views.add_qty , name='add_qty'),
    path('sub_qty/<int:orderdetails_id>' ,views.sub_qty, name='sub_qty'),
    path('payment' ,views.payment, name='payment'),
     path('show_orders',views.show_orders, name='show_orders'),
     path('prodect/order_complted',views.order_complted, name='order_complted'),
     path('verify_email/<str:username>',views.verify_email ,name='verify_email'),


]