# Generated by Django 4.2.11 on 2025-04-26 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'الاصناف',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asname', models.CharField(max_length=150, verbose_name=' اسم اللون بالانجليزى')),
                ('name', models.CharField(max_length=150, verbose_name='اسم اللون')),
                ('color', models.ImageField(upload_to='color/%Y/%m/%d/', verbose_name='صورة المنتج')),
                ('qucolor', models.IntegerField(blank=True, null=True, verbose_name='الكميه')),
            ],
            options={
                'verbose_name': 'اضافة الوان',
            },
        ),
        migrations.CreateModel(
            name='FF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gx', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='اسم التاجر')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='العنوان وتفاصيل التاجر')),
                ('number', models.CharField(blank=True, max_length=150, null=True, verbose_name='رقم الهاتف')),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('gx_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'اضافة تاجر',
            },
        ),
        migrations.CreateModel(
            name='Sise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisel', models.IntegerField(blank=True, null=True, verbose_name='المقاس')),
                ('qusise', models.IntegerField(blank=True, null=True, verbose_name='الكميه')),
                ('productsise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsises', to='product.color')),
            ],
            options={
                'verbose_name': 'اضافة المقاسات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المنتج')),
                ('asname', models.CharField(blank=True, max_length=150, null=True, verbose_name=' اسم المنتج بالانجليزى')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('asdescription', models.TextField(verbose_name='الوصف بالانجليزى')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='سعر البيع')),
                ('price_decint', models.IntegerField(blank=True, null=True, verbose_name='سعر الوهمي')),
                ('pricels', models.IntegerField(blank=True, null=True, verbose_name='السعر الحقيقى للتاجر')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='المجموع')),
                ('qus', models.IntegerField(blank=True, default='1', max_length=150, null=True, verbose_name='قيمة الموسوق')),
                ('qu', models.IntegerField(blank=True, null=True, verbose_name='الكمية')),
                ('qur', models.IntegerField(blank=True, null=True, verbose_name='الكميه الصلية')),
                ('statusu', models.CharField(blank=True, default='none', max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=' photo/%Y/%m/%d/', verbose_name='صورة المنتج')),
                ('photos', models.ImageField(blank=True, null=True, upload_to=' photos/%Y/%m/%d/', verbose_name=' صورة للمنتج اضافيه')),
                ('is_active', models.BooleanField(default=False, verbose_name='التفعيل')),
                ('facat', models.BooleanField(default=False, verbose_name='تفعيل الفقات المتعدده')),
                ('desconts', models.BooleanField(default=False, verbose_name='منتجات خصم')),
                ('qudesconts', models.IntegerField(blank=True, max_length=150, null=True, verbose_name='قيمة الخصم')),
                ('pro_date', models.DateTimeField(auto_now_add=True, verbose_name='تريخ بداية المنتج')),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2025, 4, 26, 11, 27, 36, 964039), verbose_name='تريخ بداية المنتج')),
                ('update_pro', models.DateTimeField(blank=True, null=True)),
                ('boonimg', models.BooleanField(default=False, verbose_name='الوان اضافيه')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name=' التصنيف')),
                ('gx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.gx', verbose_name='اسم التاجر')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updte', to=settings.AUTH_USER_MODEL)),
                ('user_updete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prouser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'المنتجات',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Ma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qu', models.CharField(blank=True, default='0', max_length=150, null=True, verbose_name=' القيمه الواصله')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name=' اسم الصارف')),
                ('nots', models.CharField(blank=True, max_length=150, null=True, verbose_name='  ملحوظة الصارف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='photosi/%Y/%m/%d/', verbose_name='صورة المنتج')),
                ('quimg', models.IntegerField(verbose_name='الكميه')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المنتج')),
                ('asname', models.CharField(max_length=150, verbose_name=' اسم المنتج بالانجليزى')),
                ('i', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Img', to='product.product')),
            ],
            options={
                'verbose_name': 'اضافة صور',
            },
        ),
        migrations.CreateModel(
            name='Gxqu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qu', models.CharField(blank=True, default='0', max_length=150, null=True, verbose_name=' القيمه الواصله')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('gx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.gx')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fintion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usus', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('order_detils', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('fintion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fintion', to='product.product')),
                ('order_idsid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fintion_order', to='orders.order')),
            ],
            options={
                'verbose_name': 'متبعة للمنتج',
            },
        ),
        migrations.AddField(
            model_name='color',
            name='productcolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productcolors', to='product.product'),
        ),
    ]
