# Generated by Django 5.2 on 2025-05-05 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_publish_date_alter_product_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ma',
            options={'verbose_name': 'المصارف'},
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 10, 48, 23, 658662), verbose_name='تريخ بداية المنتج'),
        ),
    ]
