# Generated by Django 4.2.11 on 2025-04-26 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massages', models.TextField(max_length=4000)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField(max_length=4000)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='post')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfiles', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='accounts.video')),
            ],
            options={
                'verbose_name': ' التعليقات ',
            },
        ),
    ]
