# Generated by Django 4.2.11 on 2025-04-26 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osp_code', models.CharField(default='242351', max_length=6)),
                ('tp_created_at', models.DateTimeField(auto_now_add=True)),
                ('opt_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('userimg', models.ImageField(blank=True, null=True, upload_to=' photo/%Y/%m/%d/', verbose_name='صورة اليوزر')),
                ('zip_number', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captaion', models.CharField(blank=True, max_length=200, verbose_name='اسم المعلن')),
                ('views', models.PositiveBigIntegerField(default='0')),
                ('prise', models.IntegerField(blank=True, null=True, verbose_name='السعر')),
                ('tp_created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField(blank=True, max_length=11, verbose_name='تليفون ')),
                ('video', models.FileField(upload_to='video/%y', verbose_name='الفيديو')),
                ('like', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
