# Generated by Django 4.2.11 on 2025-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='osp_code',
            field=models.CharField(default='2fdc1a', max_length=6),
        ),
    ]
