# Generated by Django 5.2 on 2025-05-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otptoken_osp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='osp_code',
            field=models.CharField(default='bc9a70', max_length=6),
        ),
    ]
