# Generated by Django 4.2.11 on 2025-04-26 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم ')),
                ('tital', models.CharField(blank=True, max_length=150, null=True, verbose_name='العنوان ')),
                ('number', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم الهاتف  ')),
            ],
            options={
                'verbose_name': 'المصاريف',
            },
        ),
        migrations.CreateModel(
            name='Deportpartener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uus', models.IntegerField(blank=True, null=True, verbose_name='قيمة  الواصل')),
                ('reportpostas_date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 26, 11, 27, 36, 972034), null=True)),
                ('is_finished', models.BooleanField(verbose_name='انتهاء')),
            ],
            options={
                'verbose_name': 'راجع شركات الشحن',
            },
        ),
        migrations.CreateModel(
            name='Mo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo', models.CharField(blank=True, max_length=150, null=True, verbose_name='المحافظه')),
                ('na', models.IntegerField(blank=True, null=True, verbose_name='قيمة شحن المحافظه')),
            ],
            options={
                'verbose_name': 'المحافطه',
            },
        ),
        migrations.CreateModel(
            name='Mr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr', models.CharField(blank=True, max_length=150, null=True, verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'المراكز',
            },
        ),
        migrations.CreateModel(
            name='Namepartener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الشركه')),
                ('tital', models.CharField(blank=True, max_length=150, null=True, verbose_name='العنوان ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=' الاميل ')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='رقم الهاتف  ')),
            ],
            options={
                'verbose_name': 'شركات الشكن',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, default=datetime.datetime(2025, 4, 26, 11, 27, 36, 970035), null=True)),
                ('order_delete', models.DateTimeField(auto_now_add=True)),
                ('order_updated', models.DateTimeField(blank=True, null=True)),
                ('order_update', models.DateTimeField(auto_now=True)),
                ('status_copping', models.CharField(blank=True, max_length=50, null=True, verbose_name=' حالة شركة الشحن ')),
                ('is_finished', models.BooleanField()),
                ('is_st', models.BooleanField(default=False, verbose_name=' هل تممة على طلب شركة الشحن')),
                ('posta', models.BooleanField(blank=True, null=True, verbose_name='تفعيل بوسطه')),
                ('statusu', models.CharField(blank=True, default='none', max_length=50, null=True, verbose_name='حالة عمل الطاب')),
                ('coin', models.IntegerField(blank=True, default='0', null=True, verbose_name='العموله')),
                ('status', models.CharField(blank=True, choices=[('اوردر جديد', 'اوردر جديد'), ('تم التاكيد', 'تم التاكيد'), ('تم التوصيل', 'تم التوصيل'), ('اوردر ملغى', 'اوردر ملغى'), ('عدم رد', 'عدم رد'), ('اتشحن', 'اتشحن'), (' مرتج', 'مرتج'), ('فى التوصيل', 'فى التوصيل'), ('sold', 'sold')], default='اوردر جديد', max_length=50, null=True, verbose_name='حالة الطلب')),
                ('is_Orderpartener', models.BooleanField(default=False, verbose_name='تفعيل شركات الشحن')),
                ('total_pasta', models.IntegerField(blank=True, default='0', null=True, verbose_name='وصل بوصته')),
            ],
            options={
                'verbose_name': 'الطلبات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reportpostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الواصل')),
                ('uus', models.IntegerField(blank=True, null=True, verbose_name='قيمة  الواصل')),
                ('reportpostas_date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 26, 11, 27, 36, 976032), null=True)),
                ('is_finished', models.BooleanField()),
            ],
            options={
                'verbose_name': 'تقرير بوسطه',
            },
        ),
        migrations.CreateModel(
            name='Reportpartener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uus', models.IntegerField(blank=True, null=True, verbose_name='قيمة  الواصل')),
                ('reportpostas_date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 26, 11, 27, 36, 971034), null=True)),
                ('is_finished', models.BooleanField(verbose_name='انتهاء')),
                ('id_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.order')),
                ('ramepartener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportparteners', to='orders.namepartener', verbose_name='شركة الشحن')),
                ('user_add', models.ForeignKey(blank=True, max_length=77, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'واصل شركات الشحن',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_address', models.CharField(blank=True, default='لايوجد', max_length=150, null=True, verbose_name='العنوان')),
                ('shipment_phone', models.CharField(blank=True, default='لايوجد', max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('shipment_phone_to', models.CharField(blank=True, default='لايوجد', max_length=50, null=True, verbose_name='رقم هاتف اخر')),
                ('districtid', models.CharField(blank=True, default='لايوجد', max_length=50, null=True, verbose_name='تفاصيل اكثر')),
                ('name', models.CharField(blank=True, default='لايوجد', max_length=50, null=True, verbose_name='الاسم')),
                ('mo', models.CharField(blank=True, max_length=150, null=True, verbose_name='المحافظه')),
                ('na', models.IntegerField(blank=True, null=True, verbose_name='قيمة شحن المحافظه')),
                ('mr', models.CharField(blank=True, max_length=150, null=True, verbose_name='المركز')),
                ('momr', models.CharField(blank=True, max_length=150, null=True, verbose_name='الملحوظات')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'الدفع',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_secret', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر')),
                ('quantity', models.IntegerField(verbose_name='الكميه')),
                ('s', models.IntegerField(blank=True, null=True, verbose_name='الواصل')),
                ('testing', models.IntegerField(blank=True, default='0', null=True, verbose_name='setion')),
                ('ba', models.IntegerField(blank=True, default='0', null=True, verbose_name='الكميه المستلمه')),
                ('size', models.IntegerField(blank=True, default='0', null=True, verbose_name='المقاس')),
                ('colar', models.CharField(blank=True, max_length=50, null=True, verbose_name='الون')),
                ('nameimg', models.CharField(blank=True, max_length=50, null=True, verbose_name=' تفعيل لى صوره اضافيه')),
                ('copping', models.IntegerField(blank=True, default='0', max_length=50, null=True, verbose_name=' الكميه الراجعه ')),
                ('str', models.IntegerField(default='5')),
                ('persent', models.IntegerField(default='100')),
                ('imgf', models.CharField(blank=True, max_length=250, null=True)),
                ('OrderDetailsimg', models.ImageField(upload_to='OrderDetails/%Y/%m/%d/', verbose_name=' الون اضافيه')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderss', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'الفواتير',
            },
        ),
    ]
