# Generated by Django 4.2.11 on 2025-04-26 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('product', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='order',
            name='Orderpartener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Orderpartener', to='orders.reportpartener', verbose_name='تابع لى شركة الشحن'),
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(related_name='orderDetails', through='orders.OrderDetails', to='product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_updete',
            field=models.ForeignKey(blank=True, max_length=77, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updetes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mr',
            name='mo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mos', to='orders.mo'),
        ),
        migrations.AddField(
            model_name='deportpartener',
            name='ramepartener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.namepartener', verbose_name='اختر شركة شحن'),
        ),
        migrations.AddField(
            model_name='deportpartener',
            name='user_add',
            field=models.ForeignKey(blank=True, max_length=77, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clint',
            index=models.Index(fields=['-name'], name='orders_clin_name_945cc0_idx'),
        ),
        migrations.CreateModel(
            name='Tp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.mr',),
        ),
    ]
