# Generated by Django 4.2.11 on 2025-04-26 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportpartener',
            name='reportpostas_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 26, 11, 31, 55, 396413), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 26, 11, 31, 55, 394415), null=True),
        ),
        migrations.AlterField(
            model_name='reportpartener',
            name='reportpostas_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 26, 11, 31, 55, 395414), null=True),
        ),
        migrations.AlterField(
            model_name='reportpostas',
            name='reportpostas_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 26, 11, 31, 55, 400411), null=True),
        ),
    ]
