# Generated by Django 5.2 on 2025-05-05 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_deportpartener_reportpostas_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Payment_status',
            field=models.CharField(blank=True, choices=[('COD', ' COD '), ('  CAARD  ', 'CAARD')], default='  CAARD  ', max_length=50, null=True, verbose_name='خيار الدفع'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_pay',
            field=models.CharField(blank=True, choices=[(' تم الدفع  ', ' تم الدفع  '), (' لم يتم الدفع ', ' لم يتم الدفع ')], default=' لم يتم الدفع ', max_length=50, null=True, verbose_name='حالة الدفع'),
        ),
        migrations.AlterField(
            model_name='deportpartener',
            name='reportpostas_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 5, 10, 48, 23, 689909), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 5, 5, 10, 48, 23, 689909), null=True),
        ),
        migrations.AlterField(
            model_name='reportpartener',
            name='reportpostas_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 5, 10, 48, 23, 689909), null=True),
        ),
        migrations.AlterField(
            model_name='reportpostas',
            name='reportpostas_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 5, 10, 48, 23, 696422), null=True),
        ),
    ]
